# Copyright (C) 2026 NextERP Romania
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
from odoo.tests import tagged

from .common import TestStockCommonPriceDiff


@tagged("post_install", "-at_install")
class TestAccountMovePriceDiffSourceDocs(TestStockCommonPriceDiff):
    def test_price_diff_source_docs_smart_buttons(self):
        # Un aviz de receptie fara nota contabila la receptie, urmata de
        # factura cu diferenta de pret, e scenariul in care se genereaza
        # efectiv o nota contabila pentru diferenta (contul din factura,
        # 408100, e diferit de contul de stoc 371000). La factura directa,
        # fara aviz, contul din factura e acelasi cu cel de stoc, deci nu se
        # mai genereaza o nota contabila separata (vezi
        # test_purchase.py::test_nir_with_invoice_and_diff), asa ca nu ar
        # exista nicio nota contabila de legat la factura/aviz.
        po = self.create_po(vals={"l10n_ro_notice": True})
        self.create_invoice(self.diff_p1, self.diff_p2)

        # l10n_ro_invoice_id is also written onto the plain receipt SVL by
        # the generic invoice/stock-move traceability in
        # l10n_ro_stock_account (AccountMove.action_post), regardless of any
        # price difference. Restrict to the SVLs actually generated by the
        # price-difference landed cost, same as
        # _compute_l10n_ro_price_diff_source_docs does, otherwise diff_moves
        # below also picks up the receipt's own journal entry.
        price_diff_svl = self.env["stock.valuation.layer"].search(
            [
                ("l10n_ro_invoice_id", "=", self.invoice.id),
                ("stock_landed_cost_id", "!=", False),
            ]
        )
        self.assertTrue(price_diff_svl)
        diff_moves = price_diff_svl.account_move_id
        self.assertTrue(diff_moves)

        for move in diff_moves:
            self.assertEqual(move.l10n_ro_price_diff_invoice_ids, self.invoice)
            self.assertEqual(move.l10n_ro_price_diff_picking_ids, po.picking_ids)

            action = move.action_view_l10n_ro_price_diff_invoices()
            self.assertEqual(action["res_id"], self.invoice.id)
            self.assertEqual(action["views"], [(False, "form")])

            action = move.action_view_l10n_ro_price_diff_pickings()
            self.assertEqual(action["res_id"], po.picking_ids.id)
            self.assertEqual(action["views"], [(False, "form")])

    def test_price_diff_source_docs_empty_without_price_diff(self):
        self.create_po()
        self.create_invoice()

        move = self.invoice
        self.assertFalse(move.l10n_ro_price_diff_invoice_ids)
        self.assertFalse(move.l10n_ro_price_diff_picking_ids)

        action = move.action_view_l10n_ro_price_diff_invoices()
        self.assertEqual(action["domain"], [("id", "in", [])])

        action = move.action_view_l10n_ro_price_diff_pickings()
        self.assertEqual(action["domain"], [("id", "in", [])])
