# Copyright (C) 2014 Forest and Biomass Romania
# Copyright (C) 2020 NextERP Romania
# Copyright (C) 2020 Terrabit
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
from odoo import fields, models


class stock_picking(models.Model):
    _inherit = "stock.picking"

    # Prin acest camp se indica daca un produs care e stocabil trece prin
    # contul 408 / 418 la achizitie sau vanzare
    # receptie/ livrare in baza de aviz
    notice = fields.Boolean(
        "Is a notice",
        states={"done": [("readonly", True)], "cancel": [("readonly", True)]},
        default=False,
        help="With this field the reception/delivery is set as a notice. "
        "The generated account move will contain accounts 408/418.",
    )
    # just for a view, check if still needed or we cna do it with window action
    acc_move_line_ids = fields.One2many(
        "account.move.line",
        compute="_compute_acc_move_line_ids",
        string="Generated accounting lines",
        help="Lines generated by this picking as sum of all stock.moves.",
    )

    def _compute_acc_move_line_ids(self):
        "just to show in view"
        for record in self:
            acc_move_ids = self.env["account.move"].search(
                [("stock_move_id", "in", record.move_lines.ids)]
            )
            acc_move_line_ids = self.env["account.move.line"].search(
                [("move_id", "in", acc_move_ids.ids)]
            )
            record.acc_move_line_ids = [(6, 0, acc_move_line_ids.ids)]
