[project]
name = "odoo-addons-oca-l10n-romania"
version = "19.0.20260106.0"
dependencies = [
    "odoo-addon-l10n_ro_account==19.0.*",
    "odoo-addon-l10n_ro_account_period_close==19.0.*",
    "odoo-addon-l10n_ro_account_report_invoice==19.0.*",
    "odoo-addon-l10n_ro_city==19.0.*",
    "odoo-addon-l10n_ro_config==19.0.*",
    "odoo-addon-l10n_ro_fiscal_validation==19.0.*",
    "odoo-addon-l10n_ro_nondeductible_vat==19.0.*",
    "odoo-addon-l10n_ro_partner_create_by_vat==19.0.*",
    "odoo-addon-l10n_ro_partner_unique==19.0.*",
    "odoo-addon-l10n_ro_payment_receipt_report==19.0.*",
    "odoo-addon-l10n_ro_payment_to_statement==19.0.*",
    "odoo-addon-l10n_ro_pos==19.0.*",
    "odoo-addon-l10n_ro_stock==19.0.*",
    "odoo-addon-l10n_ro_stock_account==19.0.*",
    "odoo-addon-l10n_ro_stock_account_date==19.0.*",
    "odoo-addon-l10n_ro_stock_account_date_wizard==19.0.*",
    "odoo-addon-l10n_ro_stock_account_landed_cost==19.0.*",
    "odoo-addon-l10n_ro_stock_account_tracking==19.0.*",
    "odoo-addon-l10n_ro_stock_report==19.0.*",
    "odoo-addon-l10n_ro_vat_on_payment==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
