[project]
name = "odoo-addons-oca-l10n-romania"
version = "18.0.20250509.2"
dependencies = [
    "odoo-addon-l10n_ro_account==18.0.*",
    "odoo-addon-l10n_ro_account_bank_statement_import_mt940_base==18.0.*",
    "odoo-addon-l10n_ro_account_bank_statement_import_mt940_ing==18.0.*",
    "odoo-addon-l10n_ro_account_edit_currency_rate==18.0.*",
    "odoo-addon-l10n_ro_account_period_close==18.0.*",
    "odoo-addon-l10n_ro_account_report_invoice==18.0.*",
    "odoo-addon-l10n_ro_city==18.0.*",
    "odoo-addon-l10n_ro_config==18.0.*",
    "odoo-addon-l10n_ro_fiscal_validation==18.0.*",
    "odoo-addon-l10n_ro_message_spv==18.0.*",
    "odoo-addon-l10n_ro_nondeductible_vat==18.0.*",
    "odoo-addon-l10n_ro_partner_create_by_vat==18.0.*",
    "odoo-addon-l10n_ro_partner_unique==18.0.*",
    "odoo-addon-l10n_ro_pos==18.0.*",
    "odoo-addon-l10n_ro_stock==18.0.*",
    "odoo-addon-l10n_ro_stock_account==18.0.*",
    "odoo-addon-l10n_ro_stock_account_date==18.0.*",
    "odoo-addon-l10n_ro_stock_account_date_wizard==18.0.*",
    "odoo-addon-l10n_ro_stock_account_landed_cost==18.0.*",
    "odoo-addon-l10n_ro_stock_account_notice==18.0.*",
    "odoo-addon-l10n_ro_stock_account_tracking==18.0.*",
    "odoo-addon-l10n_ro_stock_picking_comment_template==18.0.*",
    "odoo-addon-l10n_ro_stock_picking_valued_report==18.0.*",
    "odoo-addon-l10n_ro_stock_price_difference==18.0.*",
    "odoo-addon-l10n_ro_stock_report==18.0.*",
    "odoo-addon-l10n_ro_vat_on_payment==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
