[project]
name = "odoo-addons-oca-l10n-romania"
version = "19.0.20251003.2"
dependencies = [
    "odoo-addon-l10n_ro_city==19.0.*",
    "odoo-addon-l10n_ro_config==19.0.*",
    "odoo-addon-l10n_ro_stock==19.0.*",
    "odoo-addon-l10n_ro_vat_on_payment==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
